server:
  port: 8080
  servlet:
    context-path: /moto

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/moto_gp"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true